### ISSUE TITLE
Bug: Wraping <a> tag with <slide> breaks slider

### ISSUE THREAD

**Issue by tetshi** [SSENSE/vue-carousel#150]
For example: 

```
<slide>
    <a href="/page">Link</a>
</slide>
<slide>
    <a href="/page">Link</a>
</slide>
```
If you click and drag, as soon as you let off, it activates the link. I would think the expected result would be if the slide was initiated, the <a> would cease to function.

**Comment by quinnlangille** [comment]
Hey @tetshi, haven't seen this happen before, and am currently using the slide as pictures above in production. Do you mind sending a jsfiddle or a link to this happening live somewhere? Will be easier to debug from there

**Comment by tetshi** [comment]
```
<carousel :per-page="1">
     @foreach($featuredArticles as $a)
          <slide>
               <a class="no-underline" href="/article/{{$a->id}}">
                    <div class="black-overlay mb-3 h-96 p-4 relative bg-cover" style="background-image: url('{{asset($a->thumbnail)}}');">
                         <span class="absolute z-50 pin-b font-title uppercase text-white text-4xl mb-4 flex">{{$a->title}}</span>
                 </div>
             </a>
         </slide>
     @endforeach
</carousel>
```

Now this is being done in Laravel, but the end-markup is the same. For whatever reason though, if I click and drag and left off over the same slide, it'll activate the link.

**Comment by Rusya13** [comment]
Hi guys, I have the same problem. Do you have any idea how to solve it, even with some hack?

**Comment by michaelscheurer** [comment]
I have the exact same probleme with an <img tag. As soon as you click on the slider, the image appears. But at the beginning, there is nothing to see.

**Comment by stop2stare** [comment]
Hey @tetshi , have you tried to `preventDefault` when clicked on `<a>`? Though it's still going to fail in mobile devices.
I think maybe issue #174 is related to this issue. We're working on this problem.

**Comment by tetshi** [comment]
@stop2stare I did not try that, no. I don't mind the console warns temporarily, and I'm pumped you guys were able to figure out the issue. Thanks for the update. I'll try the `preventDefault` for now. Thanks!

**Comment by stop2stare** [comment]
@tetshi Haha, don't be in such a hurry. I've pushed a PR which is going to solve this problem. Maybe the maintainers will release a new version. Just wait a day.😄

**Comment by quinnlangille** [comment]
Just released now! If you pull `0.7.1` on master this should be good. @tetshi, let us know if that resolves your issue!

**Comment by matamune94** [comment]
The current version has not been resolved, need fix please

**Comment by quinnlangille** [comment]
Hey @matamune94 this was resolved quite a while ago, what version of the carousel are you using?

**Comment by matamune94** [comment]
final version sir

**Comment by matamune94** [comment]
@quinnlangille Im use nuxtjs with vuetify and vue-carousel .

**Comment by quinnlangille** [comment]
@matamune94 final version meaning `0.18.0-aplha`?

**Comment by matamune94** [comment]
@quinnlangille i use npm install maybe is true ?

**Comment by matamune94** [comment]
@quinnlangille
https://www.jsdelivr.com/package/npm/vue-carousel
I think is last version

**Comment by matamune94** [comment]
this my https://jsfiddle.net/matamune94/okbj871y/6/ when u click on numbers on sides and drag. it will have bropblem

**Comment by matamune94** [comment]
check please
![Alt Text](https://previews.dropbox.com/p/orig/AAX6FI3qXEDUU1UpoKNVMU87pO1MIKC8NpDQOn2eGHGdHMl_4-T5j6BAJjML2iTVxCHI_HJf4j2fW2ebcFlEMwvlCj-W_jBjCEhiinOW3c3bnCOHgkyF71vul-mhLSwTqYij91CSr21MjvkxPXf-Gc-WS8DXmSms-yN0pW39Beyz9wIq5aUzxYVb0ivCHOqMrJvD-Mxmz7-c1z2R8NDDebzPIsEAeYWox_8wRXcEFBJOl2s8P-SuTqKtuGkiKC3v5uZXokaF71-6AeesdgN5uNNQ/p.gif?size=1600x1200&size_mode=3)

**Comment by quinnlangille** [comment]
Hey @matamune94, I'm not able to recreate using the jsFiddle you sent above. Perhaps its a browser setting or something else on your end causing the issue?
![link_scroll](https://user-images.githubusercontent.com/17895168/54545417-062c9900-4978-11e9-948e-7bf629f1d775.gif)

**Comment by matamune94** [comment]
> Hey @matamune94, I'm not able to recreate using the jsFiddle you sent above. Perhaps its a browser setting or something else on your end causing the issue?
> ![link_scroll](https://user-images.githubusercontent.com/17895168/54545417-062c9900-4978-11e9-948e-7bf629f1d775.gif)
> 
> If I actually click the link the redirect to google happens, but that seems expected to me. Lemme know if I'm missing something

i said you click on numbers not slide sir

**Comment by matamune94** [comment]
@quinnlangille https://jsfiddle.net/matamune94/okbj871y/26/ , im fixed example , please try again

**Comment by quinnlangille** [comment]
This is still working exactly as I would expect, no different from my video posted above. If I explicitly click on the slide, it opens the link, otherwise the dragging works as expected.

**Comment by matamune94** [comment]
> This is still working exactly as I would expect, no different from my video posted above. If I explicitly click on the slide, it opens the link, otherwise the dragging works as expected.

tôi đã thử trên nhiều máy tính khác nhau và nó có cùng vấn đề như vậy , you should consider this issue carefully. I really like this carousel

**Comment by matamune94** [comment]
> This is still working exactly as I would expect, no different from my video posted above. If I explicitly click on the slide, it opens the link, otherwise the dragging works as expected.

I tried on many different computers but it had the same problem that I gave, You should thoroughly examine this issue sir, I really like it

**Comment by quinnlangille** [comment]
Sorry @matamune94 but we are not able to do anything about an issue that we cannot reproduce. I'm going to close this issue now, as from what I can tell this issue has been resolved since `0.7.1`, as stated above.

**Comment by rereradu** [comment]
Hi. I am running into the same issue as the OP. 
I was able to reproduce the issue on @matamune94 's example (https://jsfiddle.net/matamune94/okbj871y/26/), on Windows 10, Chrome 75.0.3770.142, Firefox 68.0 and Microsoft Edge 44.18362.1.0 (Microsoft EdgeHTML 18.18362). 
When releasing the mouse button from drag the link will be opened.

**Comment by dervondenbergen** [comment]
Hello,
I am have the same issue currently. I tried to reproduce it as good as possible in this CodePen:
https://codepen.io/dervondenbergen/pen/d1669fa528de1438c9990db79a6b1f55

When releasing the mouse, the link or button gets triggered. When releasing the mouse outside of the view or on another element, it won't get triggered.
![vue-carousel-bug](https://user-images.githubusercontent.com/2054024/65586465-7dc12d80-df84-11e9-865d-9976d8e178a8.gif)

I am running `vue-carousel@0.18.0` on Ubuntu 18.04.3 in Firefox 69.0.1 (64-Bit)

**Comment by kaskar2008** [comment]
Still relevant

**Comment by aeharding** [comment]
Still happens. If you drag the mouse outside of the carousel it doesn't seem to trigger. Latest Chrome and carousel.

**Comment by LukaszGrabowski1** [comment]
Any solutions ?
